### ISSUE TITLE
训练数据集会开源嘛

### ISSUE THREAD

**Issue by aidejieceng** [chanchimin/RQ-RAG#1]
感谢您的工作，请问训练数据会开源吗？构造训练集的过程数据会同步开放吗？

**Comment by chanchimin** [comment]
Thank you for your interests, our paper is currently under review, we plan to release our curated data and checkpoint after the review process. I close the issue now, feel free to open if you have further question.

**Comment by datalee** [comment]
啥时候会开源数据和ckpt？

**Comment by Caleb66666** [comment]
是否可以放出少量的、三类均有的数据作为参考，以便于更好的理解
