### ISSUE TITLE
This repo not actually executed, please claim it in README

### ISSUE THREAD

**Issue by tpoisonooo** [chanchimin/RQ-RAG#4]
Same as  #3,  in `llm_agent/__init__.py`,  
```bash
from .modelbest_rewriter import ModelBestRewriterLMAgent
```
while `modelbest_rewriter` not exist,  I doubt that the repo actullay not executed before. 

If you just want to post something to arXiv to claim a spot, **please mark that this repository has not been tested**.

**Comment by tpoisonooo** [comment]
Placing a bunch of unexecuted code is no better than leaving nothing at all.

**Comment by chanchimin** [comment]
Sorry for any inconvenience caused. I have tested the data curation code just now and added the corresponding statement in README. I will thoroughly review the fine-tuning and sampling code over the next few days. Closing the issue for now, but please feel free to reopen it if needed!
